console.log("crear una publicación en facebook");
console.log("creo un álbum de fotos");
console.log("elijo un título para el álbum");
console.log("selecciono las fotos en mi PC");
console.log("subo las fotos seleccionadas");
console.log("agrego una descripción a cada foto");
console.log("agrego colaboradores para que suban sus propias fotos");
console.log("etiqueto algunos amigos");
console.log("reviso destinatarios de la publicación");
console.log("guardo y publico el álbum");
console.log("me encanta");