console.log("granjera1");
console.log("avanzo y levanto");
console.log("avanzo y levanto");
console.log("avanzo y levanto");
console.log("avanzo y levanto");
console.log("giro a la izquierda");
console.log("avanzo y levanto");
console.log("avanzo y levanto");
console.log("avanzo y levanto");
console.log("avanzo y levanto");
console.log("avanzo y levanto");
